from django.urls import path

from . import views

app_name = "board"

urlpatterns = [
    path("", views.home, name="home"),
    path("board/", views.post_list, name="post_list"),
    path("board/new/", views.post_create, name="post_create"),
    path("board/<int:post_id>/", views.post_detail, name="post_detail"),
    path("board/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("board/<int:post_id>/delete/", views.post_delete, name="post_delete"),
    path("board/<int:post_id>/images/<int:image_id>/delete/", views.post_image_delete, name="post_image_delete"),
    path("board/<int:post_id>/like/", views.post_like, name="post_like"),
    path("board/<int:post_id>/like/json/", views.post_like_json, name="post_like_json"),
    path("link/<int:link_id>/like/", views.link_like, name="link_like"),
    path("info/<int:info_id>/like/", views.info_like, name="info_like"),
    path("menu3/", views.link_list, name="link_list"),
    path("menu3/new/", views.info_create, name="link_create"),
    path("matches/", views.match_list, name="match_list"),
    path("popular/", views.popular_list, name="popular_list"),
    path("menu4/", views.menu4, name="menu4"),
    path("menu5/", views.menu5, name="menu5"),
    path("menu5/new/", views.secret_create, name="secret_create"),
    path("menu5/<int:post_id>/", views.secret_detail, name="secret_detail"),
    path("menu5/<int:post_id>/edit/", views.secret_edit, name="secret_edit"),
    path("menu5/<int:post_id>/delete/", views.secret_delete, name="secret_delete"),
    path("menu6/", views.menu6, name="menu6"),
    path("menu6/new/", views.link_create, name="link_create_best"),
    path("menu7/", views.menu7, name="menu7"),
    path("menu7/new/", views.menu7_create, name="menu7_create"),
    path("menu8/", views.menu8, name="menu8"),
    path("menu8/new/", views.menu8_create, name="menu8_create"),
    path("menu9/", views.menu9, name="menu9"),
    path("menu9/new/", views.menu9_create, name="menu9_create"),
    path("menu10/", views.menu10, name="menu10"),
    path("menu10/new/", views.menu10_create, name="menu10_create"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("password/reset/", views.password_reset, name="password_reset"),
    path("password/change/", views.password_change, name="password_change"),
    path("profile/", views.profile, name="profile"),
]
