# Generated by Django 6.0 on 2025-12-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='익명', max_length=20),
        ),
    ]
