# Generated by Django 6.0 on 2025-12-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_linkpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
