# Generated by Django 6.0 on 2025-12-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='익명', max_length=20),
        ),
    ]
