# Generated by Django 6.0 on 2025-12-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_merge_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpost',
            name='category',
            field=models.CharField(choices=[('info', '정보'), ('best', '베스트야')], default='info', max_length=10, verbose_name='카테고리'),
        ),
    ]
