# Generated by Django 5.2.9 on 2025-12-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_comment_id_alter_linkpost_id_alter_post_id_and_more'),
        ('board', '0012_linkpost_category'),
    ]

    operations = [
    ]
