# Generated by Django 5.2.9 on 2025-12-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_comment_id_alter_linkpost_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpost',
            name='category',
            field=models.CharField(choices=[('info', '정보'), ('best', '베스트야'), ('xart', '조공모음'), ('soccer', '축구소식'), ('baseball', '야구소식'), ('stock', '주식소문')], default='info', max_length=10, verbose_name='카테고리'),
        ),
    ]
