# Generated by Django 5.2.9 on 2025-12-29 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_alter_linkpost_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
