# Generated by Django 5.2.9 on 2025-12-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_linkpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpost',
            name='content',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='linkpost',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
