# Generated by Django 5.2.9 on 2025-12-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_linkpost_content_alter_linkpost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='common', max_length=20),
        ),
    ]
