# Generated by Django 5.2.9 on 2025-12-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpost',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
