# Generated by Django 5.2.9 on 2025-12-30 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_linkpost_is_recommended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='linkpost',
            name='is_recommended',
        ),
        migrations.AlterField(
            model_name='linkpost',
            name='category',
            field=models.CharField(choices=[('best', '베스트야'), ('xart', '조공모음'), ('soccer', '축구소식'), ('baseball', '야구소식'), ('stock', '주식소문')], default='best', max_length=10, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='linkpost',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='InfoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=140)),
                ('author', models.CharField(default='익명', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_infoposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
