# Generated by Django 5.2.9 on 2025-12-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_remove_linkpost_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpost',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
