# Generated by Django 5.2.9 on 2025-12-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_linkpost_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoccerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=32, unique=True)),
                ('round_num', models.CharField(blank=True, max_length=20, null=True)),
                ('match_date', models.DateTimeField()),
                ('league', models.CharField(max_length=20)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'soccer_matches',
                'ordering': ['match_date'],
            },
        ),
    ]
