# Generated by Django 5.2.9 on 2025-12-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_soccermatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpost',
            name='link_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
