# Generated by Django 5.2.9 on 2025-12-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_linkpost_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpost',
            name='category',
            field=models.CharField(choices=[('best', '베스트야'), ('xart', '조공모음'), ('movie', '영화소식'), ('baseball', '야구소식'), ('stock', '주식소문')], default='best', max_length=10, verbose_name='카테고리'),
        ),
    ]
