# Generated by Django 5.2.9 on 2025-12-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_alter_linkpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopost',
            name='category',
            field=models.CharField(default='thread', max_length=20),
        ),
    ]
