# Generated by Codex on 2026-04-30

from django.db import migrations, models


def copy_scores(apps, schema_editor):
    SoccerMatch = apps.get_model('board', 'SoccerMatch')
    for match in SoccerMatch.objects.all():
        if match.home_score is not None and match.away_score is not None:
            match.score = f"{match.home_score}-{match.away_score}"
            match.save(update_fields=['score'])


def restore_scores(apps, schema_editor):
    SoccerMatch = apps.get_model('board', 'SoccerMatch')
    for match in SoccerMatch.objects.exclude(score__isnull=True).exclude(score=''):
        parts = match.score.split('-', 1)
        if len(parts) != 2:
            continue
        try:
            match.home_score = int(parts[0].strip())
            match.away_score = int(parts[1].strip())
        except ValueError:
            continue
        match.save(update_fields=['home_score', 'away_score'])


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_infopost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccermatch',
            name='score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(copy_scores, restore_scores),
        migrations.RemoveField(
            model_name='soccermatch',
            name='home_score',
        ),
        migrations.RemoveField(
            model_name='soccermatch',
            name='away_score',
        ),
    ]
