# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_soccermatch_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpost',
            name='category',
            field=models.CharField(choices=[('best', '베스트야'), ('xart', '조공모음'), ('movie', '영화소식'), ('itnews', 'IT 뉴스'), ('ground', '부동산'), ('stock', '주식소문')], default='best', max_length=10, verbose_name='카테고리'),
        ),
    ]
