# Generated by Codex on 2026-07-20

from django.db import migrations, models


def add_year_column_if_missing(apps, schema_editor):
    SoccerMatch = apps.get_model('board', 'SoccerMatch')
    table_name = SoccerMatch._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }
    if 'year' in existing_columns:
        return

    field = models.PositiveSmallIntegerField(null=True, blank=True)
    field.set_attributes_from_name('year')
    schema_editor.add_field(SoccerMatch, field)


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_alter_linkpost_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_year_column_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='soccermatch',
                    name='year',
                    field=models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
        ),
    ]
