# Generated by Codex on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0029_soccermatch_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccermatch',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soccermatch',
            name='liked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
