# Generated by Codex on 2026-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0032_soccermatch_result_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
